// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: api/marine/v1/marine.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarineService_GetHistoryByUser_FullMethodName        = "/marine.v1.MarineService/GetHistoryByUser"
	MarineService_GetHistoryByHistoryId_FullMethodName   = "/marine.v1.MarineService/GetHistoryByHistoryId"
	MarineService_AddHistory_FullMethodName              = "/marine.v1.MarineService/AddHistory"
	MarineService_GetCreatureByCreatureId_FullMethodName = "/marine.v1.MarineService/GetCreatureByCreatureId"
	MarineService_DeleteByCreatureId_FullMethodName      = "/marine.v1.MarineService/DeleteByCreatureId"
	MarineService_UpdateCreature_FullMethodName          = "/marine.v1.MarineService/UpdateCreature"
	MarineService_AddCreature_FullMethodName             = "/marine.v1.MarineService/AddCreature"
)

// MarineServiceClient is the client API for MarineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 海洋生物服务
type MarineServiceClient interface {
	// 获取当前用户的所有历史记录
	GetHistoryByUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetHistoryByUserResponse, error)
	// 根据历史记录ID获取单条记录
	GetHistoryByHistoryId(ctx context.Context, in *GetHistoryByHistoryIdRequest, opts ...grpc.CallOption) (*GetHistoryByHistoryIdResponse, error)
	// 添加一条新的识别历史记录
	AddHistory(ctx context.Context, in *AddHistoryRequest, opts ...grpc.CallOption) (*AddHistoryResponse, error)
	// 根据生物ID获取生物信息
	GetCreatureByCreatureId(ctx context.Context, in *GetCreatureByCreatureIdRequest, opts ...grpc.CallOption) (*GetCreatureByCreatureIdResponse, error)
	// 根据生物ID删除一条生物记录
	DeleteByCreatureId(ctx context.Context, in *DeleteByCreatureIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新生物信息
	UpdateCreature(ctx context.Context, in *UpdateCreatureRequest, opts ...grpc.CallOption) (*UpdateCreatureResponse, error)
	// 添加一条新的生物记录
	AddCreature(ctx context.Context, in *AddCreatureRequest, opts ...grpc.CallOption) (*AddCreatureResponse, error)
}

type marineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarineServiceClient(cc grpc.ClientConnInterface) MarineServiceClient {
	return &marineServiceClient{cc}
}

func (c *marineServiceClient) GetHistoryByUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetHistoryByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryByUserResponse)
	err := c.cc.Invoke(ctx, MarineService_GetHistoryByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marineServiceClient) GetHistoryByHistoryId(ctx context.Context, in *GetHistoryByHistoryIdRequest, opts ...grpc.CallOption) (*GetHistoryByHistoryIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryByHistoryIdResponse)
	err := c.cc.Invoke(ctx, MarineService_GetHistoryByHistoryId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marineServiceClient) AddHistory(ctx context.Context, in *AddHistoryRequest, opts ...grpc.CallOption) (*AddHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddHistoryResponse)
	err := c.cc.Invoke(ctx, MarineService_AddHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marineServiceClient) GetCreatureByCreatureId(ctx context.Context, in *GetCreatureByCreatureIdRequest, opts ...grpc.CallOption) (*GetCreatureByCreatureIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCreatureByCreatureIdResponse)
	err := c.cc.Invoke(ctx, MarineService_GetCreatureByCreatureId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marineServiceClient) DeleteByCreatureId(ctx context.Context, in *DeleteByCreatureIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MarineService_DeleteByCreatureId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marineServiceClient) UpdateCreature(ctx context.Context, in *UpdateCreatureRequest, opts ...grpc.CallOption) (*UpdateCreatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCreatureResponse)
	err := c.cc.Invoke(ctx, MarineService_UpdateCreature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marineServiceClient) AddCreature(ctx context.Context, in *AddCreatureRequest, opts ...grpc.CallOption) (*AddCreatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCreatureResponse)
	err := c.cc.Invoke(ctx, MarineService_AddCreature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarineServiceServer is the server API for MarineService service.
// All implementations must embed UnimplementedMarineServiceServer
// for forward compatibility.
//
// 海洋生物服务
type MarineServiceServer interface {
	// 获取当前用户的所有历史记录
	GetHistoryByUser(context.Context, *emptypb.Empty) (*GetHistoryByUserResponse, error)
	// 根据历史记录ID获取单条记录
	GetHistoryByHistoryId(context.Context, *GetHistoryByHistoryIdRequest) (*GetHistoryByHistoryIdResponse, error)
	// 添加一条新的识别历史记录
	AddHistory(context.Context, *AddHistoryRequest) (*AddHistoryResponse, error)
	// 根据生物ID获取生物信息
	GetCreatureByCreatureId(context.Context, *GetCreatureByCreatureIdRequest) (*GetCreatureByCreatureIdResponse, error)
	// 根据生物ID删除一条生物记录
	DeleteByCreatureId(context.Context, *DeleteByCreatureIdRequest) (*emptypb.Empty, error)
	// 更新生物信息
	UpdateCreature(context.Context, *UpdateCreatureRequest) (*UpdateCreatureResponse, error)
	// 添加一条新的生物记录
	AddCreature(context.Context, *AddCreatureRequest) (*AddCreatureResponse, error)
	mustEmbedUnimplementedMarineServiceServer()
}

// UnimplementedMarineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarineServiceServer struct{}

func (UnimplementedMarineServiceServer) GetHistoryByUser(context.Context, *emptypb.Empty) (*GetHistoryByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoryByUser not implemented")
}
func (UnimplementedMarineServiceServer) GetHistoryByHistoryId(context.Context, *GetHistoryByHistoryIdRequest) (*GetHistoryByHistoryIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoryByHistoryId not implemented")
}
func (UnimplementedMarineServiceServer) AddHistory(context.Context, *AddHistoryRequest) (*AddHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHistory not implemented")
}
func (UnimplementedMarineServiceServer) GetCreatureByCreatureId(context.Context, *GetCreatureByCreatureIdRequest) (*GetCreatureByCreatureIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCreatureByCreatureId not implemented")
}
func (UnimplementedMarineServiceServer) DeleteByCreatureId(context.Context, *DeleteByCreatureIdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByCreatureId not implemented")
}
func (UnimplementedMarineServiceServer) UpdateCreature(context.Context, *UpdateCreatureRequest) (*UpdateCreatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCreature not implemented")
}
func (UnimplementedMarineServiceServer) AddCreature(context.Context, *AddCreatureRequest) (*AddCreatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCreature not implemented")
}
func (UnimplementedMarineServiceServer) mustEmbedUnimplementedMarineServiceServer() {}
func (UnimplementedMarineServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarineServiceServer will
// result in compilation errors.
type UnsafeMarineServiceServer interface {
	mustEmbedUnimplementedMarineServiceServer()
}

func RegisterMarineServiceServer(s grpc.ServiceRegistrar, srv MarineServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarineService_ServiceDesc, srv)
}

func _MarineService_GetHistoryByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarineServiceServer).GetHistoryByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarineService_GetHistoryByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarineServiceServer).GetHistoryByUser(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarineService_GetHistoryByHistoryId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryByHistoryIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarineServiceServer).GetHistoryByHistoryId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarineService_GetHistoryByHistoryId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarineServiceServer).GetHistoryByHistoryId(ctx, req.(*GetHistoryByHistoryIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarineService_AddHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarineServiceServer).AddHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarineService_AddHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarineServiceServer).AddHistory(ctx, req.(*AddHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarineService_GetCreatureByCreatureId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCreatureByCreatureIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarineServiceServer).GetCreatureByCreatureId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarineService_GetCreatureByCreatureId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarineServiceServer).GetCreatureByCreatureId(ctx, req.(*GetCreatureByCreatureIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarineService_DeleteByCreatureId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByCreatureIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarineServiceServer).DeleteByCreatureId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarineService_DeleteByCreatureId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarineServiceServer).DeleteByCreatureId(ctx, req.(*DeleteByCreatureIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarineService_UpdateCreature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCreatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarineServiceServer).UpdateCreature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarineService_UpdateCreature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarineServiceServer).UpdateCreature(ctx, req.(*UpdateCreatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarineService_AddCreature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCreatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarineServiceServer).AddCreature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarineService_AddCreature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarineServiceServer).AddCreature(ctx, req.(*AddCreatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarineService_ServiceDesc is the grpc.ServiceDesc for MarineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marine.v1.MarineService",
	HandlerType: (*MarineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHistoryByUser",
			Handler:    _MarineService_GetHistoryByUser_Handler,
		},
		{
			MethodName: "GetHistoryByHistoryId",
			Handler:    _MarineService_GetHistoryByHistoryId_Handler,
		},
		{
			MethodName: "AddHistory",
			Handler:    _MarineService_AddHistory_Handler,
		},
		{
			MethodName: "GetCreatureByCreatureId",
			Handler:    _MarineService_GetCreatureByCreatureId_Handler,
		},
		{
			MethodName: "DeleteByCreatureId",
			Handler:    _MarineService_DeleteByCreatureId_Handler,
		},
		{
			MethodName: "UpdateCreature",
			Handler:    _MarineService_UpdateCreature_Handler,
		},
		{
			MethodName: "AddCreature",
			Handler:    _MarineService_AddCreature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/marine/v1/marine.proto",
}
