// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: api/marine/v1/marine.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 根据ID获取生物的请求
type GetCreatureByCreatureIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creatureid    uint32                 `protobuf:"varint,1,opt,name=creatureid,proto3" json:"creatureid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreatureByCreatureIdRequest) Reset() {
	*x = GetCreatureByCreatureIdRequest{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreatureByCreatureIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreatureByCreatureIdRequest) ProtoMessage() {}

func (x *GetCreatureByCreatureIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreatureByCreatureIdRequest.ProtoReflect.Descriptor instead.
func (*GetCreatureByCreatureIdRequest) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{0}
}

func (x *GetCreatureByCreatureIdRequest) GetCreatureid() uint32 {
	if x != nil {
		return x.Creatureid
	}
	return 0
}

// 根据ID获取生物的响应
type GetCreatureByCreatureIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creature      *MarineCreature        `protobuf:"bytes,1,opt,name=creature,proto3" json:"creature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreatureByCreatureIdResponse) Reset() {
	*x = GetCreatureByCreatureIdResponse{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreatureByCreatureIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreatureByCreatureIdResponse) ProtoMessage() {}

func (x *GetCreatureByCreatureIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreatureByCreatureIdResponse.ProtoReflect.Descriptor instead.
func (*GetCreatureByCreatureIdResponse) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{1}
}

func (x *GetCreatureByCreatureIdResponse) GetCreature() *MarineCreature {
	if x != nil {
		return x.Creature
	}
	return nil
}

// 根据ID删除生物的请求
type DeleteByCreatureIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creatureid    uint32                 `protobuf:"varint,1,opt,name=creatureid,proto3" json:"creatureid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByCreatureIdRequest) Reset() {
	*x = DeleteByCreatureIdRequest{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByCreatureIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByCreatureIdRequest) ProtoMessage() {}

func (x *DeleteByCreatureIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByCreatureIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteByCreatureIdRequest) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteByCreatureIdRequest) GetCreatureid() uint32 {
	if x != nil {
		return x.Creatureid
	}
	return 0
}

// 更新生物的请求
type UpdateCreatureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 修改：将 ID 提升为顶层字段
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// creature 对象现在只需要包含需要更新的字段，ID 可以不包含在内
	Creature      *MarineCreature `protobuf:"bytes,2,opt,name=creature,proto3" json:"creature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCreatureRequest) Reset() {
	*x = UpdateCreatureRequest{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCreatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCreatureRequest) ProtoMessage() {}

func (x *UpdateCreatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCreatureRequest.ProtoReflect.Descriptor instead.
func (*UpdateCreatureRequest) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCreatureRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCreatureRequest) GetCreature() *MarineCreature {
	if x != nil {
		return x.Creature
	}
	return nil
}

// 更新生物的响应
type UpdateCreatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creature      *MarineCreature        `protobuf:"bytes,1,opt,name=creature,proto3" json:"creature,omitempty"` // 返回更新后的完整生物信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCreatureResponse) Reset() {
	*x = UpdateCreatureResponse{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCreatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCreatureResponse) ProtoMessage() {}

func (x *UpdateCreatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCreatureResponse.ProtoReflect.Descriptor instead.
func (*UpdateCreatureResponse) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCreatureResponse) GetCreature() *MarineCreature {
	if x != nil {
		return x.Creature
	}
	return nil
}

// 添加生物的请求
type AddCreatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCreatureRequest) Reset() {
	*x = AddCreatureRequest{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCreatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCreatureRequest) ProtoMessage() {}

func (x *AddCreatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCreatureRequest.ProtoReflect.Descriptor instead.
func (*AddCreatureRequest) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{5}
}

func (x *AddCreatureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCreatureRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddCreatureRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// 添加生物的响应
type AddCreatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatureId    uint32                 `protobuf:"varint,1,opt,name=creature_id,json=creatureId,proto3" json:"creature_id,omitempty"` // 返回新创建的生物ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCreatureResponse) Reset() {
	*x = AddCreatureResponse{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCreatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCreatureResponse) ProtoMessage() {}

func (x *AddCreatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCreatureResponse.ProtoReflect.Descriptor instead.
func (*AddCreatureResponse) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{6}
}

func (x *AddCreatureResponse) GetCreatureId() uint32 {
	if x != nil {
		return x.CreatureId
	}
	return 0
}

// 历史记录信息
type History struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryId     uint64                 `protobuf:"varint,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	CreatureId    uint32                 `protobuf:"varint,4,opt,name=creature_id,json=creatureId,proto3" json:"creature_id,omitempty"`
	ResultText    string                 `protobuf:"bytes,5,opt,name=result_text,json=resultText,proto3" json:"result_text,omitempty"`
	IdentifyTime  int64                  `protobuf:"varint,6,opt,name=identify_time,json=identifyTime,proto3" json:"identify_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{7}
}

func (x *History) GetHistoryId() uint64 {
	if x != nil {
		return x.HistoryId
	}
	return 0
}

func (x *History) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *History) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *History) GetCreatureId() uint32 {
	if x != nil {
		return x.CreatureId
	}
	return 0
}

func (x *History) GetResultText() string {
	if x != nil {
		return x.ResultText
	}
	return ""
}

func (x *History) GetIdentifyTime() int64 {
	if x != nil {
		return x.IdentifyTime
	}
	return 0
}

// 海洋生物信息
type MarineCreature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatureId    uint32                 `protobuf:"varint,1,opt,name=creature_id,json=creatureId,proto3" json:"creature_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CreateTime    int64                  `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarineCreature) Reset() {
	*x = MarineCreature{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarineCreature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarineCreature) ProtoMessage() {}

func (x *MarineCreature) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarineCreature.ProtoReflect.Descriptor instead.
func (*MarineCreature) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{8}
}

func (x *MarineCreature) GetCreatureId() uint32 {
	if x != nil {
		return x.CreatureId
	}
	return 0
}

func (x *MarineCreature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarineCreature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MarineCreature) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MarineCreature) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// ... (其他 History 相关消息定义) ...
type GetHistoryByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Histories     []*History             `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryByUserResponse) Reset() {
	*x = GetHistoryByUserResponse{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryByUserResponse) ProtoMessage() {}

func (x *GetHistoryByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryByUserResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryByUserResponse) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{9}
}

func (x *GetHistoryByUserResponse) GetHistories() []*History {
	if x != nil {
		return x.Histories
	}
	return nil
}

type GetHistoryByHistoryIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Historyid     uint64                 `protobuf:"varint,1,opt,name=historyid,proto3" json:"historyid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryByHistoryIdRequest) Reset() {
	*x = GetHistoryByHistoryIdRequest{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryByHistoryIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryByHistoryIdRequest) ProtoMessage() {}

func (x *GetHistoryByHistoryIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryByHistoryIdRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryByHistoryIdRequest) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{10}
}

func (x *GetHistoryByHistoryIdRequest) GetHistoryid() uint64 {
	if x != nil {
		return x.Historyid
	}
	return 0
}

type GetHistoryByHistoryIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       *History               `protobuf:"bytes,1,opt,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryByHistoryIdResponse) Reset() {
	*x = GetHistoryByHistoryIdResponse{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryByHistoryIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryByHistoryIdResponse) ProtoMessage() {}

func (x *GetHistoryByHistoryIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryByHistoryIdResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryByHistoryIdResponse) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{11}
}

func (x *GetHistoryByHistoryIdResponse) GetHistory() *History {
	if x != nil {
		return x.History
	}
	return nil
}

type AddHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	CreatureId    uint32                 `protobuf:"varint,2,opt,name=creature_id,json=creatureId,proto3" json:"creature_id,omitempty"`
	ResultText    string                 `protobuf:"bytes,3,opt,name=result_text,json=resultText,proto3" json:"result_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHistoryRequest) Reset() {
	*x = AddHistoryRequest{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHistoryRequest) ProtoMessage() {}

func (x *AddHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHistoryRequest.ProtoReflect.Descriptor instead.
func (*AddHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{12}
}

func (x *AddHistoryRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AddHistoryRequest) GetCreatureId() uint32 {
	if x != nil {
		return x.CreatureId
	}
	return 0
}

func (x *AddHistoryRequest) GetResultText() string {
	if x != nil {
		return x.ResultText
	}
	return ""
}

type AddHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryId     uint64                 `protobuf:"varint,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHistoryResponse) Reset() {
	*x = AddHistoryResponse{}
	mi := &file_api_marine_v1_marine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHistoryResponse) ProtoMessage() {}

func (x *AddHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_marine_v1_marine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHistoryResponse.ProtoReflect.Descriptor instead.
func (*AddHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_marine_v1_marine_proto_rawDescGZIP(), []int{13}
}

func (x *AddHistoryResponse) GetHistoryId() uint64 {
	if x != nil {
		return x.HistoryId
	}
	return 0
}

var File_api_marine_v1_marine_proto protoreflect.FileDescriptor

const file_api_marine_v1_marine_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/marine/v1/marine.proto\x12\tmarine.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"@\n" +
	"\x1eGetCreatureByCreatureIdRequest\x12\x1e\n" +
	"\n" +
	"creatureid\x18\x01 \x01(\rR\n" +
	"creatureid\"X\n" +
	"\x1fGetCreatureByCreatureIdResponse\x125\n" +
	"\bcreature\x18\x01 \x01(\v2\x19.marine.v1.MarineCreatureR\bcreature\";\n" +
	"\x19DeleteByCreatureIdRequest\x12\x1e\n" +
	"\n" +
	"creatureid\x18\x01 \x01(\rR\n" +
	"creatureid\"^\n" +
	"\x15UpdateCreatureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x125\n" +
	"\bcreature\x18\x02 \x01(\v2\x19.marine.v1.MarineCreatureR\bcreature\"O\n" +
	"\x16UpdateCreatureResponse\x125\n" +
	"\bcreature\x18\x01 \x01(\v2\x19.marine.v1.MarineCreatureR\bcreature\"g\n" +
	"\x12AddCreatureRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\"6\n" +
	"\x13AddCreatureResponse\x12\x1f\n" +
	"\vcreature_id\x18\x01 \x01(\rR\n" +
	"creatureId\"\xc5\x01\n" +
	"\aHistory\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\x04R\thistoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1f\n" +
	"\vcreature_id\x18\x04 \x01(\rR\n" +
	"creatureId\x12\x1f\n" +
	"\vresult_text\x18\x05 \x01(\tR\n" +
	"resultText\x12#\n" +
	"\ridentify_time\x18\x06 \x01(\x03R\fidentifyTime\"\xa5\x01\n" +
	"\x0eMarineCreature\x12\x1f\n" +
	"\vcreature_id\x18\x01 \x01(\rR\n" +
	"creatureId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\x03R\n" +
	"createTime\"L\n" +
	"\x18GetHistoryByUserResponse\x120\n" +
	"\thistories\x18\x01 \x03(\v2\x12.marine.v1.HistoryR\thistories\"<\n" +
	"\x1cGetHistoryByHistoryIdRequest\x12\x1c\n" +
	"\thistoryid\x18\x01 \x01(\x04R\thistoryid\"M\n" +
	"\x1dGetHistoryByHistoryIdResponse\x12,\n" +
	"\ahistory\x18\x01 \x01(\v2\x12.marine.v1.HistoryR\ahistory\"r\n" +
	"\x11AddHistoryRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1f\n" +
	"\vcreature_id\x18\x02 \x01(\rR\n" +
	"creatureId\x12\x1f\n" +
	"\vresult_text\x18\x03 \x01(\tR\n" +
	"resultText\"3\n" +
	"\x12AddHistoryResponse\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\x04R\thistoryId2\x9d\a\n" +
	"\rMarineService\x12o\n" +
	"\x10GetHistoryByUser\x12\x16.google.protobuf.Empty\x1a#.marine.v1.GetHistoryByUserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/marine/history\x12\x96\x01\n" +
	"\x15GetHistoryByHistoryId\x12'.marine.v1.GetHistoryByHistoryIdRequest\x1a(.marine.v1.GetHistoryByHistoryIdResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/marine/history/{historyid}\x12l\n" +
	"\n" +
	"AddHistory\x12\x1c.marine.v1.AddHistoryRequest\x1a\x1d.marine.v1.AddHistoryResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/marine/history\x12\x9e\x01\n" +
	"\x17GetCreatureByCreatureId\x12).marine.v1.GetCreatureByCreatureIdRequest\x1a*.marine.v1.GetCreatureByCreatureIdResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/marine/creature/{creatureid}\x12\x80\x01\n" +
	"\x12DeleteByCreatureId\x12$.marine.v1.DeleteByCreatureIdRequest\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&*$/api/v1/marine/creature/{creatureid}\x12~\n" +
	"\x0eUpdateCreature\x12 .marine.v1.UpdateCreatureRequest\x1a!.marine.v1.UpdateCreatureResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/api/v1/marine/creature/{id}\x12p\n" +
	"\vAddCreature\x12\x1d.marine.v1.AddCreatureRequest\x1a\x1e.marine.v1.AddCreatureResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/marine/creatureB\x18Z\x16yuyan/api/marine/v1;v1b\x06proto3"

var (
	file_api_marine_v1_marine_proto_rawDescOnce sync.Once
	file_api_marine_v1_marine_proto_rawDescData []byte
)

func file_api_marine_v1_marine_proto_rawDescGZIP() []byte {
	file_api_marine_v1_marine_proto_rawDescOnce.Do(func() {
		file_api_marine_v1_marine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_marine_v1_marine_proto_rawDesc), len(file_api_marine_v1_marine_proto_rawDesc)))
	})
	return file_api_marine_v1_marine_proto_rawDescData
}

var file_api_marine_v1_marine_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_marine_v1_marine_proto_goTypes = []any{
	(*GetCreatureByCreatureIdRequest)(nil),  // 0: marine.v1.GetCreatureByCreatureIdRequest
	(*GetCreatureByCreatureIdResponse)(nil), // 1: marine.v1.GetCreatureByCreatureIdResponse
	(*DeleteByCreatureIdRequest)(nil),       // 2: marine.v1.DeleteByCreatureIdRequest
	(*UpdateCreatureRequest)(nil),           // 3: marine.v1.UpdateCreatureRequest
	(*UpdateCreatureResponse)(nil),          // 4: marine.v1.UpdateCreatureResponse
	(*AddCreatureRequest)(nil),              // 5: marine.v1.AddCreatureRequest
	(*AddCreatureResponse)(nil),             // 6: marine.v1.AddCreatureResponse
	(*History)(nil),                         // 7: marine.v1.History
	(*MarineCreature)(nil),                  // 8: marine.v1.MarineCreature
	(*GetHistoryByUserResponse)(nil),        // 9: marine.v1.GetHistoryByUserResponse
	(*GetHistoryByHistoryIdRequest)(nil),    // 10: marine.v1.GetHistoryByHistoryIdRequest
	(*GetHistoryByHistoryIdResponse)(nil),   // 11: marine.v1.GetHistoryByHistoryIdResponse
	(*AddHistoryRequest)(nil),               // 12: marine.v1.AddHistoryRequest
	(*AddHistoryResponse)(nil),              // 13: marine.v1.AddHistoryResponse
	(*emptypb.Empty)(nil),                   // 14: google.protobuf.Empty
}
var file_api_marine_v1_marine_proto_depIdxs = []int32{
	8,  // 0: marine.v1.GetCreatureByCreatureIdResponse.creature:type_name -> marine.v1.MarineCreature
	8,  // 1: marine.v1.UpdateCreatureRequest.creature:type_name -> marine.v1.MarineCreature
	8,  // 2: marine.v1.UpdateCreatureResponse.creature:type_name -> marine.v1.MarineCreature
	7,  // 3: marine.v1.GetHistoryByUserResponse.histories:type_name -> marine.v1.History
	7,  // 4: marine.v1.GetHistoryByHistoryIdResponse.history:type_name -> marine.v1.History
	14, // 5: marine.v1.MarineService.GetHistoryByUser:input_type -> google.protobuf.Empty
	10, // 6: marine.v1.MarineService.GetHistoryByHistoryId:input_type -> marine.v1.GetHistoryByHistoryIdRequest
	12, // 7: marine.v1.MarineService.AddHistory:input_type -> marine.v1.AddHistoryRequest
	0,  // 8: marine.v1.MarineService.GetCreatureByCreatureId:input_type -> marine.v1.GetCreatureByCreatureIdRequest
	2,  // 9: marine.v1.MarineService.DeleteByCreatureId:input_type -> marine.v1.DeleteByCreatureIdRequest
	3,  // 10: marine.v1.MarineService.UpdateCreature:input_type -> marine.v1.UpdateCreatureRequest
	5,  // 11: marine.v1.MarineService.AddCreature:input_type -> marine.v1.AddCreatureRequest
	9,  // 12: marine.v1.MarineService.GetHistoryByUser:output_type -> marine.v1.GetHistoryByUserResponse
	11, // 13: marine.v1.MarineService.GetHistoryByHistoryId:output_type -> marine.v1.GetHistoryByHistoryIdResponse
	13, // 14: marine.v1.MarineService.AddHistory:output_type -> marine.v1.AddHistoryResponse
	1,  // 15: marine.v1.MarineService.GetCreatureByCreatureId:output_type -> marine.v1.GetCreatureByCreatureIdResponse
	14, // 16: marine.v1.MarineService.DeleteByCreatureId:output_type -> google.protobuf.Empty
	4,  // 17: marine.v1.MarineService.UpdateCreature:output_type -> marine.v1.UpdateCreatureResponse
	6,  // 18: marine.v1.MarineService.AddCreature:output_type -> marine.v1.AddCreatureResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_marine_v1_marine_proto_init() }
func file_api_marine_v1_marine_proto_init() {
	if File_api_marine_v1_marine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_marine_v1_marine_proto_rawDesc), len(file_api_marine_v1_marine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_marine_v1_marine_proto_goTypes,
		DependencyIndexes: file_api_marine_v1_marine_proto_depIdxs,
		MessageInfos:      file_api_marine_v1_marine_proto_msgTypes,
	}.Build()
	File_api_marine_v1_marine_proto = out.File
	file_api_marine_v1_marine_proto_goTypes = nil
	file_api_marine_v1_marine_proto_depIdxs = nil
}
