// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v5.29.4
// source: api/marine/v1/marine.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMarineServiceAddCreature = "/marine.v1.MarineService/AddCreature"
const OperationMarineServiceAddHistory = "/marine.v1.MarineService/AddHistory"
const OperationMarineServiceDeleteByCreatureId = "/marine.v1.MarineService/DeleteByCreatureId"
const OperationMarineServiceGetCreatureByCreatureId = "/marine.v1.MarineService/GetCreatureByCreatureId"
const OperationMarineServiceGetHistoryByHistoryId = "/marine.v1.MarineService/GetHistoryByHistoryId"
const OperationMarineServiceGetHistoryByUser = "/marine.v1.MarineService/GetHistoryByUser"
const OperationMarineServiceUpdateCreature = "/marine.v1.MarineService/UpdateCreature"

type MarineServiceHTTPServer interface {
	// AddCreature 添加一条新的生物记录
	AddCreature(context.Context, *AddCreatureRequest) (*AddCreatureResponse, error)
	// AddHistory 添加一条新的识别历史记录
	AddHistory(context.Context, *AddHistoryRequest) (*AddHistoryResponse, error)
	// DeleteByCreatureId 根据生物ID删除一条生物记录
	DeleteByCreatureId(context.Context, *DeleteByCreatureIdRequest) (*emptypb.Empty, error)
	// GetCreatureByCreatureId 根据生物ID获取生物信息
	GetCreatureByCreatureId(context.Context, *GetCreatureByCreatureIdRequest) (*GetCreatureByCreatureIdResponse, error)
	// GetHistoryByHistoryId 根据历史记录ID获取单条记录
	GetHistoryByHistoryId(context.Context, *GetHistoryByHistoryIdRequest) (*GetHistoryByHistoryIdResponse, error)
	// GetHistoryByUser 获取当前用户的所有历史记录
	GetHistoryByUser(context.Context, *emptypb.Empty) (*GetHistoryByUserResponse, error)
	// UpdateCreature 更新生物信息
	UpdateCreature(context.Context, *UpdateCreatureRequest) (*UpdateCreatureResponse, error)
}

func RegisterMarineServiceHTTPServer(s *http.Server, srv MarineServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/marine/history", _MarineService_GetHistoryByUser0_HTTP_Handler(srv))
	r.GET("/api/v1/marine/history/{historyid}", _MarineService_GetHistoryByHistoryId0_HTTP_Handler(srv))
	r.POST("/api/v1/marine/history", _MarineService_AddHistory0_HTTP_Handler(srv))
	r.GET("/api/v1/marine/creature/{creatureid}", _MarineService_GetCreatureByCreatureId0_HTTP_Handler(srv))
	r.DELETE("/api/v1/marine/creature/{creatureid}", _MarineService_DeleteByCreatureId0_HTTP_Handler(srv))
	r.PUT("/api/v1/marine/creature/{id}", _MarineService_UpdateCreature0_HTTP_Handler(srv))
	r.POST("/api/v1/marine/creature", _MarineService_AddCreature0_HTTP_Handler(srv))
}

func _MarineService_GetHistoryByUser0_HTTP_Handler(srv MarineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarineServiceGetHistoryByUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHistoryByUser(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetHistoryByUserResponse)
		return ctx.Result(200, reply)
	}
}

func _MarineService_GetHistoryByHistoryId0_HTTP_Handler(srv MarineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetHistoryByHistoryIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarineServiceGetHistoryByHistoryId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHistoryByHistoryId(ctx, req.(*GetHistoryByHistoryIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetHistoryByHistoryIdResponse)
		return ctx.Result(200, reply)
	}
}

func _MarineService_AddHistory0_HTTP_Handler(srv MarineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddHistoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarineServiceAddHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddHistory(ctx, req.(*AddHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddHistoryResponse)
		return ctx.Result(200, reply)
	}
}

func _MarineService_GetCreatureByCreatureId0_HTTP_Handler(srv MarineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCreatureByCreatureIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarineServiceGetCreatureByCreatureId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCreatureByCreatureId(ctx, req.(*GetCreatureByCreatureIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCreatureByCreatureIdResponse)
		return ctx.Result(200, reply)
	}
}

func _MarineService_DeleteByCreatureId0_HTTP_Handler(srv MarineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteByCreatureIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarineServiceDeleteByCreatureId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteByCreatureId(ctx, req.(*DeleteByCreatureIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _MarineService_UpdateCreature0_HTTP_Handler(srv MarineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCreatureRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarineServiceUpdateCreature)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCreature(ctx, req.(*UpdateCreatureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCreatureResponse)
		return ctx.Result(200, reply)
	}
}

func _MarineService_AddCreature0_HTTP_Handler(srv MarineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddCreatureRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarineServiceAddCreature)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddCreature(ctx, req.(*AddCreatureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddCreatureResponse)
		return ctx.Result(200, reply)
	}
}

type MarineServiceHTTPClient interface {
	// AddCreature 添加一条新的生物记录
	AddCreature(ctx context.Context, req *AddCreatureRequest, opts ...http.CallOption) (rsp *AddCreatureResponse, err error)
	// AddHistory 添加一条新的识别历史记录
	AddHistory(ctx context.Context, req *AddHistoryRequest, opts ...http.CallOption) (rsp *AddHistoryResponse, err error)
	// DeleteByCreatureId 根据生物ID删除一条生物记录
	DeleteByCreatureId(ctx context.Context, req *DeleteByCreatureIdRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetCreatureByCreatureId 根据生物ID获取生物信息
	GetCreatureByCreatureId(ctx context.Context, req *GetCreatureByCreatureIdRequest, opts ...http.CallOption) (rsp *GetCreatureByCreatureIdResponse, err error)
	// GetHistoryByHistoryId 根据历史记录ID获取单条记录
	GetHistoryByHistoryId(ctx context.Context, req *GetHistoryByHistoryIdRequest, opts ...http.CallOption) (rsp *GetHistoryByHistoryIdResponse, err error)
	// GetHistoryByUser 获取当前用户的所有历史记录
	GetHistoryByUser(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *GetHistoryByUserResponse, err error)
	// UpdateCreature 更新生物信息
	UpdateCreature(ctx context.Context, req *UpdateCreatureRequest, opts ...http.CallOption) (rsp *UpdateCreatureResponse, err error)
}

type MarineServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMarineServiceHTTPClient(client *http.Client) MarineServiceHTTPClient {
	return &MarineServiceHTTPClientImpl{client}
}

// AddCreature 添加一条新的生物记录
func (c *MarineServiceHTTPClientImpl) AddCreature(ctx context.Context, in *AddCreatureRequest, opts ...http.CallOption) (*AddCreatureResponse, error) {
	var out AddCreatureResponse
	pattern := "/api/v1/marine/creature"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarineServiceAddCreature))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AddHistory 添加一条新的识别历史记录
func (c *MarineServiceHTTPClientImpl) AddHistory(ctx context.Context, in *AddHistoryRequest, opts ...http.CallOption) (*AddHistoryResponse, error) {
	var out AddHistoryResponse
	pattern := "/api/v1/marine/history"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarineServiceAddHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteByCreatureId 根据生物ID删除一条生物记录
func (c *MarineServiceHTTPClientImpl) DeleteByCreatureId(ctx context.Context, in *DeleteByCreatureIdRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/marine/creature/{creatureid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarineServiceDeleteByCreatureId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCreatureByCreatureId 根据生物ID获取生物信息
func (c *MarineServiceHTTPClientImpl) GetCreatureByCreatureId(ctx context.Context, in *GetCreatureByCreatureIdRequest, opts ...http.CallOption) (*GetCreatureByCreatureIdResponse, error) {
	var out GetCreatureByCreatureIdResponse
	pattern := "/api/v1/marine/creature/{creatureid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarineServiceGetCreatureByCreatureId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetHistoryByHistoryId 根据历史记录ID获取单条记录
func (c *MarineServiceHTTPClientImpl) GetHistoryByHistoryId(ctx context.Context, in *GetHistoryByHistoryIdRequest, opts ...http.CallOption) (*GetHistoryByHistoryIdResponse, error) {
	var out GetHistoryByHistoryIdResponse
	pattern := "/api/v1/marine/history/{historyid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarineServiceGetHistoryByHistoryId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetHistoryByUser 获取当前用户的所有历史记录
func (c *MarineServiceHTTPClientImpl) GetHistoryByUser(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*GetHistoryByUserResponse, error) {
	var out GetHistoryByUserResponse
	pattern := "/api/v1/marine/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarineServiceGetHistoryByUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCreature 更新生物信息
func (c *MarineServiceHTTPClientImpl) UpdateCreature(ctx context.Context, in *UpdateCreatureRequest, opts ...http.CallOption) (*UpdateCreatureResponse, error) {
	var out UpdateCreatureResponse
	pattern := "/api/v1/marine/creature/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarineServiceUpdateCreature))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
