// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"yuyan/internal/biz"
	"yuyan/internal/conf"
	"yuyan/internal/data"
	"yuyan/internal/pkg/jwt"
	"yuyan/internal/server"
	"yuyan/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confJwt *conf.Jwt, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, db, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	jwtRepo := jwt.NewJwtRepo(confJwt)
	userUseCase := biz.NewUserUseCase(userRepo, jwtRepo)
	userService := service.NewUserService(userUseCase)
	marineCreatureRepo := data.NewMarineCreatureRepo(dataData, logger)
	historyRepo := data.NewHistoryRepo(dataData, logger)
	marineUseCase := biz.NewMarineUseCase(marineCreatureRepo, historyRepo)
	marineServiceService := service.NewMarineServiceService(marineUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, confJwt, userService, marineServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, confJwt, userService, marineServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
